
import { Router } from "express";
import * as controller from "./financial.controller.js";
import { requireAuth, requireAdmin } from "../../core/middlewares/authMiddleware.js";

const router = Router();

// ========== EMERGENCY ROUTES (NO AUTH) ==========
// FIX: Add missing columns to fixed_costs table

router.get("/fix-fixed-costs-schema", async (req, res) => {
    try {
        const { db } = await import("../../core/db/connection.js");
        const { sql } = await import("drizzle-orm");
        await db.execute(sql`ALTER TABLE fixed_costs ADD COLUMN IF NOT EXISTS total_installments integer`);
        await db.execute(sql`ALTER TABLE fixed_costs ADD COLUMN IF NOT EXISTS start_date timestamp`);
        res.json({ success: true, message: "Columns total_installments and start_date added/verified." });
    } catch (error: any) {
        res.status(500).json({ success: false, error: error.message });
    }
});

router.get("/test-recurrence", async (req, res) => {
    try {
        const { db } = await import("../../core/db/connection.js");
        const { fixedCosts, fixedCostInstallments } = await import("../../shared/schema.js");
        const { randomUUID } = await import("crypto");

        const id = randomUUID();
        const start = new Date();
        const cost = {
            id,
            name: "Teste Recorrencia " + start.toISOString(),
            value: "100.00",
            frequency: "Mensal",
            dueDay: 10,
            costTypeId: null, // nullable?
            vehicleId: null,
            vendor: "Tester",
            totalInstallments: 5,
            startDate: start,
            description: "Generated by test route",
            isActive: true
        };

        // Manual logic dump from repository to verify environment behavior
        console.log("Creating cost:", cost);
        await db.insert(fixedCosts).values(cost as any);

        const installments = [];
        for (let i = 0; i < 5; i++) {
            const dueDate = new Date(start);
            dueDate.setMonth(dueDate.getMonth() + i);
            dueDate.setDate(10);
            installments.push({
                fixedCostId: id,
                installmentNumber: i + 1,
                dueDate: dueDate,
                value: "100.00",
                status: 'Pendente'
            });
        }

        await db.insert(fixedCostInstallments).values(installments as any);

        res.json({ success: true, id, installments_count: installments.length });
    } catch (error: any) {
        console.error("Test Route Error:", error);
        res.status(500).json({ success: false, error: error.message, stack: error.stack });
    }
});


// DEBUG: Get database counts and recent data
router.get("/debug", async (req, res) => {
    try {
        const { db } = await import("../../core/db/connection.js");
        const { fixedCosts, fixedCostInstallments } = await import("../../../shared/schema.js");

        const recentCosts = await db.select().from(fixedCosts).limit(5);
        const recentInstallments = await db.select().from(fixedCostInstallments).limit(10);

        res.json({
            fixedCostsCount: recentCosts.length,
            installmentsCount: recentInstallments.length,
            recentCosts,
            recentInstallments
        });
    } catch (error: any) {
        res.status(500).json({ error: error.message });
    }
});

// ========== AUTHENTICATED ROUTES ==========
// Todas as rotas abaixo exigem autenticação
router.use(requireAuth);

router.get("/expenses", requireAdmin, controller.getExpenses);
router.get("/legacy-maintenances", requireAdmin, controller.getLegacyMaintenances);
router.post("/expenses", controller.createExpense);
router.put("/expenses/:id", controller.updateExpenseController);
router.delete("/expenses/:id", controller.deleteExpenseController);

// Cost Types
router.post("/cost-types/restore-defaults", requireAdmin, controller.restoreDefaultCostTypes);
router.get("/cost-types", controller.getCostTypes);
router.post("/cost-types", requireAdmin, controller.createCostType);
router.put("/cost-types/:id", requireAdmin, controller.updateCostType);
router.delete("/cost-types/:id", requireAdmin, controller.deleteCostType);

// Installments (Must be before /:id)
router.get("/fixed-costs/installments", requireAdmin, controller.getFixedCostInstallments);
router.put("/fixed-costs/installments/:id", requireAdmin, controller.updateFixedCostInstallment);

router.get("/fixed-costs", requireAdmin, controller.getFixedCosts);
router.post("/fixed-costs", requireAdmin, controller.createFixedCost);
router.put("/fixed-costs/:id", requireAdmin, controller.updateFixedCost);
router.delete("/fixed-costs/:id", requireAdmin, controller.deleteFixedCost);

// Rota de Emergência para corrigir Schema (executar uma vez e remover depois)
router.get("/fix-db-emergency", async (req, res) => {
    try {
        const { db } = await import("../../core/db/connection.js");
        const { sql } = await import("drizzle-orm");
        await db.execute(sql`ALTER TABLE cost_types ADD COLUMN IF NOT EXISTS icon text`);
        await db.execute(sql`ALTER TABLE cost_types ADD COLUMN IF NOT EXISTS color text`);
        await db.execute(sql`ALTER TABLE cost_types ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true`);
        res.send("DB Update: Columns icon and color added/verified successfully.");
    } catch (error: any) {
        res.status(500).send("Error updating DB: " + error.message);
    }
});

// Rota de Migração de Dados Legados (Preencher ícones/cores faltantes)
router.post("/fix-legacy-visuals", requireAdmin, async (req, res) => {
    try {
        const { migrateCostTypesVisuals } = await import("../../scripts/db/migrate_cost_types_visuals.js");
        await migrateCostTypesVisuals();
        res.json({ success: true, message: "Migração visual executada com sucesso." });
    } catch (error: any) {
        res.status(500).json({ success: false, error: error.message });
    }
});

export default router;
